# Generated by Django 6.0.1 on 2026-01-22 17:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otp',
            name='pre_auth_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
